version: '3.8'

services:
  oracle:
    image: doctorkirk/oracle-19c
    container_name: curatify_oracle
    restart: unless-stopped
    environment:
      ORACLE_PWD: rootpassword
      ORACLE_CHARACTERSET: AL32UTF8
      NLS_LANG: AMERICAN_AMERICA.AL32UTF8
    ports:
      - '1521:1521'
      - '5500:5500'
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./init.sql:/opt/oracle/scripts/setup/01-init.sql
      - ./seed-data.sql:/opt/oracle/scripts/setup/02-seed-data.sql
    networks:
      - curatify_network

  redis:
    image: redis:7-alpine
    container_name: curatify_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - curatify_network

volumes:
  oracle_data:
    driver: local
  redis_data:
    driver: local

networks:
  curatify_network:
    driver: bridge
