version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: curatify_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: curatify
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - curatify_network
    command: mongod --auth

  redis:
    image: redis:7-alpine
    container_name: curatify_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - curatify_network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  curatify_network:
    driver: bridge
